version: '3.8'

services:
  sqs_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - API_KEY=open-api-key
      - FROM_EMAIL=email
      - FROM_PASSWORD=password
      - PROVIDER=localstack #localstack #aws
      - QUEUE_NAME=transcription-queue
      - AWS_REGION=us-east-1
    volumes:
      - .:/app  # Monta o código fonte no container
    depends_on:
      - localstack
    networks:
      - localstack-network
    command: ["watchmedo", "auto-restart", "--pattern=*.py", "--recursive", "--", "python3", "-m", "src.main_sqs_consumer"]

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs,sns,iam
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - ./:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash -c "docker-entrypoint.sh & /docker-entrypoint-initaws.d/setup-localstack.sh && tail -f /dev/null"
    networks:
      - localstack-network

networks:
  localstack-network:
    external: true
