version: '3.8'

services:
  sqs_consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=access-key
      - AWS_SECRET_ACCESS_KEY=secret-key
      - API_KEY=open-api-key
      - FROM_EMAIL=email
      - FROM_PASSWORD=password
      - PROVIDER=aws
      - QUEUE_NAME=transcription-queue
      - AWS_REGION=us-east-1
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4571:4571"
