version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=your_openai_api_key
      - FROM_EMAIL=your_email@example.com
      - FROM_PASSWORD=your_email_password
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - MONGODB_URI=mongodb://mongo:27017/
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_ENDPOINT=http://localstack:4566
    depends_on:
      - mongo
      - localstack

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  mongo_data:
  localstack_data:
